### PR TITLE
Add notebook to extract LF

### PR DESCRIPTION
**Pull request by mjlp123**
Creating a notebook that extracts benchmarks like Layer Fidelity (LF), Error per Layered Gate (EPLG), and 2Q errors. This notebook can be easily adjusted to extract any other type of device information. Open to comments and suggestions.

### CODE REVIEW

**Comment by mjlp123** [comment]
Most recent updates include:

1) Updating `layer_fidelity_single_chain` notebook to import lf functions from relevant modules (simplify code and avoid replicating code) and reconstructing the best subchain for each length
2) Creating module `layer_fidelity_utils.py` with helper functions relevant to running and analyzing lf
3) Updating `fast_layer_fidelity.py` to import lf functions form relevant modules
4) Changing single line in function `path_to_edges` in `graph_utils.py` to make an edge into a tuple instead of a list of qubits

**Comment by dcmckayibm** [comment]
Thanks @mjlp123 , I started taking a look at the notebooks and I'm wondering if we should split this into 3 PRs.

Here are some comments on the `extract_benchmarks` notebook.
- Can we change the 2Q benchmarks plot to be log?
- Change to   `backend = service.backend(machine,instance='')` and default the instance to the open provider
- Change the labels to 
```
ax.set_title('2Q error distribution')
ax.set_ylabel('2Q Error')
```

- Add a 1Q properties section (similar to this)

```
# Get 1Q errors for each backend
prop_list = ['T1','T2','1Q Error','Readout Error']
prop_unit = ['us','us','','']
prop_scale = [1e-6,1e-6,1,1]
prop_ind = 0

oneqprops = {}
for machine in backend_names:
    # Get 1q gate
    backend = backends[machine]

    #nq
    nq = backend.configuration().n_qubits

    # Extract 1Q gate errors
    props = []
    for qnum in range(nq):
        if prop_ind==0:
            props.append(backend.properties().t1(qnum))
        elif prop_ind==1:
            props.append(backend.properties().t2(qnum))
        elif prop_ind==2:
            props.append(backend.properties().gate_error('sx',qnum))
        elif prop_ind==3:
            props.append(backend.properties().readout_error(qnum))
        else:
            raise ValueError('Not a valid property selection, prop_ind must be < %d'%len(prop_list))
    oneqprops[machine] = props
```

```
# Plot the distribution
fig, ax = plt.subplots(1, 1, figsize=(6, 4))
legend = []
for i, machine in enumerate(backend_names):
    #errors = [x for x in oneqprops[machine] if 0<x<1] # clip values outside of normal range
    stats.probplot(np.array(oneqprops[machine])/prop_scale[prop_ind], plot=plt, fit=False)
    ax.get_lines()[i].set_color(colors[i%len(colors)])
    plt.setp(ax.get_lines()[i], markersize=2)  #

    if machine=='ibm_cleveland':
        ax.get_lines()[i].set_marker('^')
        plt.setp(ax.get_lines()[i], markersize=4)  #
        ax.get_lines()[i].set_color('black')
    
    legend.append(machine)
ax.legend(legend, bbox_to_anchor=(1.05, 1), loc='upper left')
ax.set_title('%s distribution'%prop_list[prop_ind])
if len(prop_unit[prop_ind])>0:
    ax.set_ylabel('%s (%s)'%(prop_list[prop_ind],prop_unit[prop_ind]))
else:
    ax.set_ylabel('%s'%(prop_list[prop_ind]))
ax.figure.set_dpi(150)
ax.set_yscale('log')
plt.grid()
plt.show()
```

- Add this code at the end (ibm/qiskit copyright stuff)
-
```
import datetime
from IPython.display import HTML, display

def qiskit_copyright(line="", cell=None):
    """IBM copyright"""
    now = datetime.datetime.now()

    html = "<div style='width: 100%; background-color:#d5d9e0;"
    html += "padding-left: 10px; padding-bottom: 10px; padding-right: 10px; padding-top: 5px'>"
    html += "<p>&copy; Copyright IBM 2017, %s.</p>" % now.year
    html += "<p>This code is licensed under the Apache License, Version 2.0. You may<br>"
    html += "obtain a copy of this license in the LICENSE.txt file in the root directory<br> "
    html += "of this source tree or at http://www.apache.org/licenses/LICENSE-2.0."

    html += "<p>Any modifications or derivative works of this code must retain this<br>"
    html += "copyright notice, and modified files need to carry a notice indicating<br>"
    html += "that they have been altered from the originals.</p>"
    html += "</div>"
    return display(HTML(html))

qiskit_copyright()
```

**Comment by dcmckayibm** [comment]
I'm thinking we should add a low weight graph visualizer based on the qiskit one in graph_utilities so that we don't have to rely on the qiskit one and have extra packages installed (graphviz)

**Comment by dcmckayibm** [comment]
For `layer_fidelity_single_chain.ipynb`

- Same comment about the `instance` in backend and the code at the end of the notebook
- I got this error running the `run_lf`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 2
      1 # Run LF
----> 2 exp_data = lfu.run_lf_chain(
      3     chain=qchain,
      4     backend=backend,
      5     nseeds=nseeds,
      6     seed=seed,
      7     cliff_lengths=cliff_lengths,
      8     nshots=nshots)

File ~/gitrepos/qiskit-device-benchmarking/qiskit_device_benchmarking/utilities/layer_fidelity_utils.py:73, in run_lf_chain(chain, backend, nseeds, seed, cliff_lengths, nshots)
     71 # Decompose chain into trivial two disjoint layers (list of list of gates)
     72 print('Decomposing qubit chain into two disjoint layers')
---> 73 all_pairs = gu.path_to_edges([chain], coupling_map)[0]
     74 layers = [all_pairs[0::2], all_pairs[1::2]] # will run a layer for each list
     76 # Check that each list is in the coupling map and is disjoint

File ~/gitrepos/qiskit-device-benchmarking/qiskit_device_benchmarking/utilities/graph_utils.py:83, in path_to_edges(paths, coupling_map)
     81 if coupling_map is not None:
     82     if tmp_set not in coupling_map:
---> 83         tmp_set.reverse()
     84         if tmp_set not in coupling_map:
     85           raise ValueError('Path not found in coupling map')

AttributeError: 'tuple' object has no attribute 'reverse'
```

**Comment by dcmckayibm** [comment]
I think this is due to the change to tuples in `graph_utils` can you remind me what that was motivated by?

**Comment by mjlp123** [comment]
I'll split this PR into 3 and submit them separately @dcmckayibm

**Comment by mjlp123** [comment]
Thanks for the comments!

**Pull request closed without merging**
